// Find biggest value within three values

let a = 10,
    b = 25, 
    c = 69;

if(a > b)
{
    if(a > c)
    {
        console.log(`${a} is biggest`);
    }
}

else if(b > a)








{
    if(b > c)
    {
        console.log(`${b} is biggest`);
    }
}

else
{
    console.log(`${c} is biggest`);
}

// let val1 = 10,
// val2 = 34,
// val3 = 24;
// if (val1 > val2) 
// {
//     if (val1 > val3)
//     {
//         onsole.log(`${val1} is biggest`);
//     }
// } 
// else if (val2 > val1) {
// if (val2 > val3) {
// console.log(`${val2} is biggest`);
// }
// } else {
// console.log(`${val3} is biggest`);
// }
